spring:
  application:
    name: part3-performance

  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_deep_dive
    username: app
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG
